### ISSUE TITLE
In svg element "d" height  and circleWidth gets wrong value because of "scale()" function

### ISSUE THREAD

**Issue by ae-loggma** [hoaphantn7604/react-native-size-scaling#1]
![Screen Shot 2022-09-22 at 17 45 40](https://user-images.githubusercontent.com/98164564/191778639-a82ca7ef-f086-40d9-934b-44618428bcd3.png)

`  const height = scale(iHeight);
  const circleWidth = scale(centerWidth) + scale(16);`

"scale()" function works fine for bigger screen but in my example I use iPhone 8 emulator and there is a space bottom of SVG element. Maybe issue related to  your repo (react-native-curved-bottom-bar) however problem in function. Would you check it please ?

**Comment by hoaphantn7604** [comment]
hi @ae-loggma ,
Can you send the full code for me to check?

**Comment by ae-loggma** [comment]
> hi @ae-loggma , Can you send the full code for me to check?

Can not share too much info because of company policy, Here is the detail of bottom bar

`        <CurvedBottomBar.Navigator
          ref={tabMenu}
          strokeWidth={1}
          height={70}
          circleWidth={65}
          bgColor="#FFFFFF"
          initialRouteName="first"
          borderTopLeftRight
          renderCircle={() => <CircleComponent/>}
          tabBar={renderTabBar}>`

issue only related this device, it's looks fine for newest phones or tablets

**Comment by hoaphantn7604** [comment]
hi @ae-loggma ,
This issue is resolved.
